version : '3'
services :
    db:
        image: mariadb:10.5.8
        environment:
            MYSQL_ROOT_PASSWORD : root
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: users
        container_name: user_api_db
        ports:
            - "3306:3307"
        volumes:
            - golang-docker-data:/var/lib/mysql
    api:
        build:
            context : .
            dockerfile: Dockerfile.multistage
        ports:
            - "5100:5100"
        depends_on:
            - db
        container_name : user_api
volumes:
  golang-docker-data: