FROM golang:1.17.3  AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . ./

RUN go build -o  /ms-curso-user-api



FROM gcr.io/distroless/base-debian10 

WORKDIR /
COPY --from=build /ms-curso-user-api  /user_api

EXPOSE 5100

USER nonroot:nonroot

CMD ["/user_api"]