version : '3'
services :
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD : root
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: users
        container_name: user_api_db
        ports:
            - "3306:3306"
        volumes:
            - golang-docker-data:/var/lib/mysql
volumes:
  golang-docker-data: